---
apiVersion: v1
kind: Service
metadata:
  name: up-and-running
  namespace: app-team-1
  labels:
    app: up-and-running
    team: app-team-1
spec: 
  selector: 
    app: up-and-running
  ports: 
  - name: http
    port: 8080
    protocol: TCP