---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: up-and-running-ingress
  namespace: app-team-2
spec:
  template:
    spec:
      backend:
        serviceName: up-and-running-mcs
        servicePort: 8080
      rules:
        - host: team2.gke-at-scale.com
          backend:
            serviceName: up-and-running-mcs
            servicePort: 8080